[package]
name = "memflow-cli"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[build-dependencies]
clap = { version = "2.33.0", features = ["yaml"] }

[dependencies]
memflow-core = { git = "ssh://git@github.com/memflow/memflow.git", branch = "dev" }
memflow-win32 = { git = "ssh://git@github.com/memflow/memflow.git", branch = "dev" }
memflow-coredump = { git = "ssh://git@github.com/memflow/memflow.git", branch = "dev" }
#memflow-core = { path = "../memflow/memflow-core" }
#memflow-win32 = { path = "../memflow/memflow-win32" }
#memflow-coredump = { path = "../memflow/connectors/memflow-coredump" }
clap = { version = "2.33.0", features = ["yaml"] }
toml = "0.5"
serde = "1.0.97"
serde_derive = "1.0"
simple_logger = "1.0.1"
log = "0.4.8"
libc = "0.2.69"
pdb = { git = "https://github.com/willglynn/pdb" }
pelite = { git = "https://github.com/ko1n/pelite" }
url = "2.1.0"
win_key_codes = "0.1.2"

[target.'cfg(target_os = "linux")'.dependencies]
#memflow-qemu-procfs = { git = "ssh://git@github.com/memflow/memflow.git", branch = "dev", optional = true }
#memflow-qemu-procfs = { path = "../memflow/connectors/memflow-qemu-procfs", optional = true }

[features]
default = []
#default = ["connector-qemu-procfs"]
#connector-bridge = ["flow-bridge"]
#connector-qemu-procfs = ["memflow-qemu-procfs"]
