
[profile.bench]
debug = true

[workspace]
members = [
    "memflow-daemon",
    "memflow-cli",
    "memflow-daemon-connector",
]
default-members = [
    "memflow-daemon",
    "memflow-cli",
    "memflow-daemon-connector",
]
